# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/meeting.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/meeting.proto',
  package='meeting',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x13proto/meeting.proto\x12\x07meeting\"#\n\x13SubscriptionRequest\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\"F\n\x0bMeetingInfo\x12\x0c\n\x04\x63ity\x18\x01 \x01(\t\x12\x13\n\x0b\x66ree_places\x18\x02 \x01(\x05\x12\x14\n\x0cparticipants\x18\x03 \x03(\t2Y\n\x0eMeetingService\x12G\n\rMeetingStream\x12\x1c.meeting.SubscriptionRequest\x1a\x14.meeting.MeetingInfo\"\x00\x30\x01\x62\x06proto3'
)




_SUBSCRIPTIONREQUEST = _descriptor.Descriptor(
  name='SubscriptionRequest',
  full_name='meeting.SubscriptionRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='meeting.SubscriptionRequest.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=67,
)


_MEETINGINFO = _descriptor.Descriptor(
  name='MeetingInfo',
  full_name='meeting.MeetingInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='meeting.MeetingInfo.city', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='free_places', full_name='meeting.MeetingInfo.free_places', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='participants', full_name='meeting.MeetingInfo.participants', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=69,
  serialized_end=139,
)

DESCRIPTOR.message_types_by_name['SubscriptionRequest'] = _SUBSCRIPTIONREQUEST
DESCRIPTOR.message_types_by_name['MeetingInfo'] = _MEETINGINFO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SubscriptionRequest = _reflection.GeneratedProtocolMessageType('SubscriptionRequest', (_message.Message,), {
  'DESCRIPTOR' : _SUBSCRIPTIONREQUEST,
  '__module__' : 'proto.meeting_pb2'
  # @@protoc_insertion_point(class_scope:meeting.SubscriptionRequest)
  })
_sym_db.RegisterMessage(SubscriptionRequest)

MeetingInfo = _reflection.GeneratedProtocolMessageType('MeetingInfo', (_message.Message,), {
  'DESCRIPTOR' : _MEETINGINFO,
  '__module__' : 'proto.meeting_pb2'
  # @@protoc_insertion_point(class_scope:meeting.MeetingInfo)
  })
_sym_db.RegisterMessage(MeetingInfo)



_MEETINGSERVICE = _descriptor.ServiceDescriptor(
  name='MeetingService',
  full_name='meeting.MeetingService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=141,
  serialized_end=230,
  methods=[
  _descriptor.MethodDescriptor(
    name='MeetingStream',
    full_name='meeting.MeetingService.MeetingStream',
    index=0,
    containing_service=None,
    input_type=_SUBSCRIPTIONREQUEST,
    output_type=_MEETINGINFO,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_MEETINGSERVICE)

DESCRIPTOR.services_by_name['MeetingService'] = _MEETINGSERVICE

# @@protoc_insertion_point(module_scope)
